languageCode = "en"
languageName = "English"
weight = 1
title = "Doug Hatcher"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 1st 2006"
  logo = "img/author.jpg"
  # secondaryLogo = "PATH"
  description = "Solution Consultant and Technical Architect at Blue Acorn and Infosys"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Doug Hatcher"
  image = "img/blowfish_logo.png"
  headline = "Solution Consultant and Technical Architect at Blue Acorn and Infosys"
  bio = "Solution Consultant and Technical Architect at Blue Acorn and Infosys"
  links = [
    { x-twitter = "https://twitter.com/superterran" },
    { mastodon = "https://masto.ai/@blowfish" },
    { github = "https://github.com/superterran" },
  ]

  