languageCode = "en"
languageName = "English"
weight = 1
title = "Doug Hatcher"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 1st 2006"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Doug Hatcher"
  image = "img/blowfish_logo.png"
  headline = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  links = [
    { x-twitter = "https://twitter.com/superterran" },
    { mastodon = "https://masto.ai/@blowfish" },
    { github = "https://github.com/superterran" },
  ]

  