languageCode = "en-us"
title = "Doug Hatcher"
baseURL = ""
theme = "dopetrope"

[params.portfolio]
    title = "My Portfolio"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    googleanalytics = ""
    disqus = ""